[package]
name = "pvm"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "1.0.4"
toml = "0.7.1"
# serde = "1.0.152"
serde = {version = "1.0.152", features = ["derive"]}